using exercise1;
// Bai lam cua Pham Duc Minh
Console.WriteLine("LINE");
Line line = new Line(1, 1, 3, 2);
Console.WriteLine(line.ToString());
Console.Write("After moving: ");
line.Move(1, 0);
Console.WriteLine(line.ToString());
Console.WriteLine("---------------------------------------------");
Console.WriteLine("CIRCLE");
Circle circle = new Circle(2, 4, 3);
Console.WriteLine(circle.ToString());
Console.Write("After moving: ");
circle.Move(2, 3);
Console.WriteLine(circle.ToString());
Console.WriteLine("---------------------------------------------");
Console.WriteLine("RECTANGLE");
Rectangle rectangle = new Rectangle(2, 2, 3, 4, 6, 3);
Console.WriteLine(rectangle.ToString());
Console.Write("After moving: ");
rectangle.Move(2, 1);
Console.WriteLine(rectangle.ToString());
Console.WriteLine("---------------------------------------------");
Console.WriteLine("POLYLINE");
Polyline polyline = new Polyline(2, 5, 3, 4, 1, 3);
Console.WriteLine(polyline.ToString());
Console.Write("After moving: ");
polyline.Move(4, 5);
Console.WriteLine(polyline.ToString());